### PR TITLE
Feature/dji build

### PR DESCRIPTION
**Pull request by j005u**
Added new target type "dji" and made everything build with NDK.

### CODE REVIEW

**Comment by j005u** [comment]
This PR was submitted to the wrong repo entirely by mistake.

**Comment by j005u** [comment]
master on the same repo the PR came from.

We'll definitely look into upstreaming a few changes once we have something solid, but right now it's still a bit of a hack job.

**Comment by kisvegabor** [comment]
> We'll definitely look into upstreaming a few changes once we have something solid, but right now it's still a bit of a hack job.

It'd be great! 
A JS binding is truly amazing, and it's quite unfortunate that this repo is a little bit inactive know. :slightly_frowning_face:

**Comment by panjunweiby** [comment]
How text is displayed Chinese

**Comment by panjunweiby** [comment]
How to support Chinese input method

**Pull request closed without merging**
